spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/notes?autoReconnect=true&createDatabaseIfNotExist=true
    username: postgres
    password: postgres